/**
 * \class Candidate
 *
 * Class for candidate paths generated by the local planner.
 *
 * \author Chris Goodin
 *
 * \date 8/31/2020
 */

#ifndef SPLINE_CANDIDATE_H
#define SPLINE_CANDIDATE_H
#include <vector>
#include "nature/planning/local/polynomial.h"

namespace nature {
namespace planning{

class Candidate {
public:
	/**
	 * @brief Construct an empty candidate path.
	 * @details Leaves polynomial and scoring fields in their default state; call
	 *          Initialize before evaluation. Used by the local planner to seed
	 *          candidate lists.
	 */
	Candidate(){}

	/**
	 * @brief Construct a candidate path from a polynomial.
	 * @param p The cubic polynomial defining the path in Frenet space.
	 * @details Calls Initialize to precompute derivatives used for curvature and
	 *          safety evaluation in the local planner.
	 */ 
	Candidate(Polynomial p) {
		Initialize(p);
	}

	/**
	 * @brief Initialize the candidate path with a polynomial.
	 * @param p The cubic polynomial defining the path.
	 * @details Precomputes first/second derivatives and resets scoring flags.
	 *          Called by the local planner when generating new candidates.
	 */ 
	void Initialize(Polynomial p) {
		curve_ = p;
		first_deriv_ = curve_.Derivative();
		second_deriv_ = first_deriv_.Derivative();
		out_of_bounds_ = false;
		hits_obstacle_ = false;
		rank_ = -1;
		max_curvature_ = 0.0f;
		max_length_ = 100.0f;
		s0_ = 0.0f;
        segmentation_cost_ = 0.0f;
	}

	/**
	 * @brief Assign another candidate to this one.
	 * @param c Candidate to copy.
	 * @details Copies polynomial, derivatives, and all scoring fields.
	 */ 
	void operator = (const Candidate &c) {
		curve_ = c.curve_;
		first_deriv_ = c.first_deriv_;
		second_deriv_ = c.second_deriv_;
		out_of_bounds_ = c.out_of_bounds_;
		hits_obstacle_ = c.hits_obstacle_;
		cost_ = c.cost_;
		comfortability_ = c.comfortability_;
		static_safety_ = c.static_safety_;
		dynamic_safety_ = c.dynamic_safety_;
		segmentation_cost_ = c.segmentation_cost_;
		rank_ = c.rank_;
		max_length_ = c.max_length_;
		max_curvature_ = c.max_curvature_;
		s0_ = c.s0_;
	}

	/**
	 * @brief Evaluate lateral offset at arc length s.
	 * @param s The arc length along the path.
	 * @return Signed lateral offset (rho) at s.
	 * @details Evaluates the candidate polynomial; used for path sampling.
	 */ 
	float At(float s) { return curve_.At(s); }

	/**
	 * @brief Evaluate first derivative of lateral offset at arc length s.
	 * @param s The arc length along the path.
	 * @return First derivative of rho at s.
	 * @details Used to compute curvature and smoothness penalties.
	 */ 
	float DerivativeAt(float s) { return first_deriv_.At(s); }

	/**
	 * @brief Evaluate second derivative of lateral offset at arc length s.
	 * @param s The arc length along the path.
	 * @return Second derivative of rho at s.
	 * @details Used to compute curvature magnitude for safety checks.
	 */ 
	float SecondDerivativeAt(float s) { return second_deriv_.At(s); }

	/**
	 * @brief Check if the candidate leaves the drivable corridor.
	 * @return True if out of bounds.
	 * @details Flag set during collision and boundary checks.
	 */ 
	bool IsOutOfBounds() { return out_of_bounds_; }

	/**
	 * @brief Check if the candidate intersects an obstacle.
	 * @return True if an obstacle collision was detected.
	 * @details Flag set by collision checking against occupancy grids.
	 */ 
	bool HitsObstacle() { return hits_obstacle_; }

	/**
	 * @brief Set the out-of-bounds flag.
	 * @param oob True if the candidate goes out of bounds.
	 * @details Written by boundary checks in the local planner.
	 */ 
	void SetOutOfBounds(bool oob) { out_of_bounds_ = oob; }

	/**
	 * @brief Set the obstacle-hit flag.
	 * @param ho True if the candidate hits an obstacle.
	 * @details Written by collision checking routines.
	 */ 
	void SetHitsObstacle(bool ho) { hits_obstacle_ = ho; }

	/**
	 * @brief Set the cumulative cost of the path.
	 * @param cost The cumulative cost.
	 * @details Aggregate score used to rank candidates.
	 */ 
	void SetCost(float cost) { cost_ = cost; }

	/**
	 * @brief Get the cumulative cost of the path.
	 * @return Cumulative cost value.
	 * @details Used when selecting the best candidate.
	 */
	float GetCost() { return cost_; }

	/**
	 * @brief Set the rank of the path.
	 * @param rank Rank value (lower is better).
	 * @details Assigned by the local planner after scoring.
	 */ 
	void SetRank(int rank) { rank_ = rank; }

	/**
	 * @brief Get the rank of the path.
	 * @return Rank value.
	 * @details Used for diagnostics and selection.
	 */
	int GetRank() { return rank_; }

	/**
	 * @brief Set the maximum curvature of the path.
	 * @param mc Max curvature value.
	 * @details Stored for safety and comfort scoring.
	 */ 
	void SetMaxCurvature(float mc) { max_curvature_ = mc; }

	/**
	 * @brief Get the maximum curvature of the path.
	 * @return Max curvature value.
	 * @details Used in reporting and selection.
	 */ 
	float GetMaxCurvature() { return max_curvature_; }

	/**
	 * @brief Set the comfortability score of the path.
	 * @param comfort Comfortability score.
	 * @details Higher comfortability typically means lower curvature changes.
	 */ 
	void SetComfortability(float comfort) { comfortability_ = comfort; }

	/**
	 * @brief Get the comfortability score of the path.
	 * @return Comfortability score.
	 * @details Used by the local planner to rank candidates.
	 */ 
	float GetComfortability() { return comfortability_; }

	/**
	 * @brief Set the static safety score of the path.
	 * @param stat_safe Static safety score.
	 * @details Derived from static obstacle clearance.
	 */ 
	void SetStaticSafety(float stat_safe) { static_safety_ = stat_safe; }

	/**
	 * @brief Get the static safety score of the path.
	 * @return Static safety score.
	 * @details Used by the local planner during ranking.
	 */ 
	float GetStaticSafety() { return static_safety_; }

	/**
	 * @brief Set the dynamic safety score of the path.
	 * @param dyn_safe Dynamic safety score.
	 * @details Derived from predicted motion and dynamic obstacles.
	 */ 
	void SetDynamicSafety(float dyn_safe) { dynamic_safety_ = dyn_safe; }

	/**
	 * @brief Get the dynamic safety score of the path.
	 * @return Dynamic safety score.
	 * @details Used by the local planner during ranking.
	 */ 
	float GetDynamicSafety() { return dynamic_safety_; }

	/**
	 * @brief Set the path deviation cost.
	 * @param rho_cost Path deviation cost.
	 * @details Captures how far the candidate deviates from the centerline.
	 */ 
	void SetRhoCost(float rho_cost) { rho_final_ = rho_cost; }

	/**
	 * @brief Get the path deviation cost.
	 * @return Path deviation cost.
	 * @details Used in scoring relative to the centerline.
	 */ 
	float GetRhoCost() { return rho_final_; }

	/**
	 * @brief Set the maximum length of the path.
	 * @param ml Maximum length.
	 * @details Used to cap candidate paths in evaluation.
	 */ 
	void SetMaxLength(float ml) { max_length_ = ml; }

	/**
	 * @brief Get the maximum length of the path.
	 * @return Maximum length.
	 * @details Used by the planner to limit candidate extension.
	 */ 
	float GetMaxLength() { return max_length_; }

	/**
	 * @brief Set the initial s-value of the path.
	 * @param s0 Initial s-value with respect to the centerline.
	 * @details Used when aligning candidates to the centerline.
	 */ 
	void SetS0(float s0) { s0_ = s0; }

	/**
	 * @brief Get the initial s-value of the path.
	 * @return Initial s-value.
	 * @details Used for diagnostics and path reconstruction.
	 */ 
	float GetS0() { return s0_; }

    /**
    * @brief Set the terrain segmentation cost.
    * @param segmentation_cost Cost derived from labeled terrain.
    * @details Used to penalize candidates that cross undesirable classes.
    */
    void SetSegmentationCost(float segmentation_cost) { segmentation_cost_ = segmentation_cost; }

    /**
    * @brief Get the terrain segmentation cost.
    * @return Segmentation cost value.
    * @details Used when ranking candidates with semantic terrain data.
    */
    float GetSegmentationCost() const { return segmentation_cost_; }

private:
	Polynomial curve_;
	Polynomial first_deriv_;
	Polynomial second_deriv_;
	bool out_of_bounds_;
	bool hits_obstacle_;
	float cost_;
	float comfortability_;
	float static_safety_;
	float segmentation_cost_;
	float dynamic_safety_;
	float rho_final_;
	float max_curvature_;
	float max_length_;
	float s0_;
	int rank_;
};

} // namespace planning
} // namespace nature


#endif
